# Generated by Django 4.1.3 on 2022-12-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('join', models.DateField()),
                ('education', models.CharField(max_length=30)),
                ('empid', models.IntegerField()),
                ('exp', models.CharField(max_length=30)),
                ('pack', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
